-- AlterTable
ALTER TABLE `users` ADD COLUMN `totalPredictions` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `exactPredictions` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `correctWinnerPredictions` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `currentStreak` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maxStreak` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `avgPoints` DOUBLE NOT NULL DEFAULT 0;
